services:

  pss:
    build:
      context: ./skm-neo4j
    env_file:
      - ./skm-neo4j/.env
    volumes:
      - ./skm-neo4j/neo4j_db/logs:/logs
      - ./skm-neo4j/neo4j_db/conf:/conf
      - ./skm-neo4j/neo4j_db/data/db:/data
      - ./skm-neo4j/neo4j_db/plugins:/plugins
    ports:
      - "7475:7474"
      - "7688:7687"
    healthcheck:
      test: wget http://localhost:7687 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  build:
    image: biocypher/base:1.2.0
    container_name: build
    volumes:
      - biocypher_neo4j_volume:/usr/app/data
      - .:/src/
    command:
      - /bin/bash
      - /src/scripts/build.sh
    depends_on:
      pss:
        condition: service_healthy

  import:
    image: neo4j:4.4-enterprise
    container_name: import
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      FILL_DB_ON_STARTUP: "yes"
    volumes:
      - biocypher_neo4j_volume:/data
      - ./scripts/import.sh:/scripts/import.sh
      - ./biocypher-log/import.report:/var/lib/neo4j/import.report
    command:
      - /bin/bash
      - /scripts/import.sh
    depends_on:
      build:
        condition: service_completed_successfully

  deploy:
    image: neo4j:4.4-enterprise
    container_name: deploy
    volumes:
      - biocypher_neo4j_volume:/data
    environment:
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_databases_default__to__read__only: "false"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    depends_on:
      import:
        condition: service_completed_successfully

  biochatter:
    image: biocypher/biochatter-light:0.6.10
    container_name: biochatter
    ports:
      - "8501:8501"
    networks:
      - default
    depends_on:
      - deploy
    env_file: "app.env"
    environment:
      - DOCKER_COMPOSE=true
      - CHAT_TAB=false
      - PROMPT_ENGINEERING_TAB=false
      - RAG_TAB=false
      - CORRECTING_AGENT_TAB=false
      - KNOWLEDGE_GRAPH_TAB=true

volumes:
  biocypher_neo4j_volume:

